import './style.css';
const email='wiresandstone@gmail.com';
document.querySelector('#app').innerHTML=`
<div class="site-shell"><div class="grain"></div>
<div class="top-strip"><span>ALBERTA, CANADA • EST. 2021</span><a href="https://jaeden.pages.dev" target="_blank" rel="noreferrer">DESIGNER - HTTPS://JAEDEN.PAGES.DEV</a></div>
<header class="nav"><a class="brand" href="#top"><span class="mark"><i></i><i></i><b></b></span><span>Wires <em>&</em> STONE</span></a><nav><a href="#top">HOME</a><a href="#craft">THE CRAFT</a><a href="#catalog">CATALOG STATUS</a><a href="#inquiry">PRIVATE INQUIRY</a></nav><a class="email-pill" href="mailto:wiresandstone@gmail.com">DIRECT EMAIL <b>↗</b></a></header>
<main id="top">
<section class="hero wrap"><div class="hero-copy reveal"><div class="eyebrow">RAW MINERAL ART</div><h1>Be elegant,<br><i>feel elegant.</i></h1><div class="script">Connect with the wires, and walk with the stones.</div><p>Bespoke, handcrafted mineral wire art by Wires & Stone. Hand-wrapped around natural raw crystals and unheated gems. Tailored by private arrangement.</p><div class="actions"><a class="btn dark" href="https://www.instagram.com/wiresandstone" target="_blank" rel="noreferrer">VISIT @WIRESANDSTONE <b>↗</b></a><a class="btn light" href="#inquiry">PRIVATE COMMISSION <b>+</b></a></div><div class="micro">HANDCRAFTED PRECISION <span>·</span> PRIVATE ARRANGEMENT <span>·</span> ALBERTA, CANADA</div></div>
<div class="hero-art reveal"><div class="glow"></div><div class="arch"><div class="arch-in"><div class="gem g1"></div><div class="gem g2"></div><div class="gem g3"></div><div class="wire w1"></div><div class="wire w2"></div><div class="wire w3"></div><div class="seal">W<span>&</span>S</div></div></div><div class="art-meta"><span>01 / 03</span><strong>Wires & Stone</strong><span>RAW MINERAL ART</span></div></div></section>
<section class="band"><span class="num">01</span><div><span class="script-small">Wires & Stone</span><strong>RAW MINERAL ART</strong><p>Artisan hand-woven wire wrapping around natural gemstones and raw mineral points.</p></div><span class="origin">Alberta, Canada • Est. 2021</span></section>
<section class="wrap craft" id="craft"><div class="heading reveal"><span class="script-label">HISTORY</span><h2>Based in Alberta,<br><i>Canada</i></h2><div class="rule"><b></b><b></b><b></b></div></div><div class="craft-grid"><article class="history reveal"><div class="smallrow"><span>ESTABLISHED 2021</span><span>W&S / 001</span></div><div class="history-mark">W<span>&</span>S</div><p>Founded in 2021, Wires & Stone was created to connect raw mineral beauty with intricate wire wrapping.</p><div class="smallrow bottom"><span>HANDCRAFTED</span><span>ALBERTA</span></div></article><div><div class="craft-intro reveal"><span class="script-label">Established 2021</span><h3>Handcrafted Precision</h3><strong>Here's Some Information:</strong></div><div class="craft-text reveal"><p>At Wires & Stone, each piece begins with hand-selected raw crystals. Through delicate wire wrapping, and precise cold tension techniques, every design highlights the natural beauty of the stone(s), and gem(s) chosen, for your own beautiful piece.</p><p>Specific metallic wire selections, chain styles, and custom gem requests are tailored entirely by private arrangement. Reach out directly to discuss bespoke commissions or special stone wraps.</p></div><div class="specs"><div class="spec reveal"><b>◇</b><span><strong>Raw Crystals</strong><small>Authentic natural mineral points</small></span><i>↗</i></div><div class="spec reveal"><b>⌁</b><span><strong>Custom Wraps</strong><small>Hand-manipulated wire weaving</small></span><i>↗</i></div><div class="spec reveal"><b>✦</b><span><strong>Private Request</strong><small>Arranged by direct email</small></span><i>↗</i></div></div></div></div></section>
<section class="wrap catalog" id="catalog"><div class="heading centered reveal"><span class="script-label">Digital Catalog</span><h2>Gallery Status</h2><div class="rule"><b></b><b></b><b></b></div></div><article class="catalog-card reveal"><div class="catalog-orbit"><div class="orbit"></div><div class="catalog-gem"></div><span>W&S</span></div><div class="catalog-copy"><span class="status">● CURRENTLY BUILDING</span><h3>GALLERY UNDER CONSTRUCTION</h3><div class="script-small">Work in Progress</div><p>The web catalog is currently under construction, while I navigate production of the website. All custom requests and available inventory are managed by private arrangement.</p><p>To view my beautiful pieces, crystal wraps, and past work, please visit my official Instagram account directly at @wiresandstone.</p><a class="btn dark" href="https://www.instagram.com/wiresandstone" target="_blank" rel="noreferrer">VISIT INSTAGRAM @WIRESANDSTONE <b>↗</b></a></div><span class="vertical">CATALOG / 00</span></article></section>
<section class="wrap inquiry" id="inquiry"><article class="inquiry-card reveal"><div class="inquiry-orbit"><div class="orbit"></div><div class="catalog-gem"></div><span>W&S</span></div><div class="inquiry-copy"><span class="script-label">Inquiries</span><h2>Private Arrangement</h2><p>For custom raw stone wraps, commission details, or private inquiries, please reach out directly via email.</p><div class="actions"><a class="btn dark" href="mailto:wiresandstone@gmail.com">OPEN E-MAIL SERVICE <b>↗</b></a><button class="btn light" id="copy" type="button">COPY EMAIL ADDRESS <b>▣</b></button></div><div class="direct">Direct Email: <span>wiresandstone@gmail.com</span></div></div></article></section>
</main>
<footer><div class="footer-top"><div><small>WIRES & STONE / PRIVATE MINERAL ART</small><h2>Crafted by hand.<br><i>Secured by design.</i></h2></div><span>ALBERTA, CANADA<br>EST. 2021</span></div><div class="security-grid"><article class="security green"><div class="security-top">[ LEAD ARCHITECT & DEVELOPER ] <b>01</b></div><div class="badge"><div class="seal">JV</div><div><small>VERIFIED DESIGNER</small><strong>SYSTEM ARCHITECT & LEAD ENGINEER</strong></div></div><p>DESIGNED AND CODED BY MR. JAEDEN VALLÉE</p><div class="statusline">DESIGN SYSTEM / ACTIVE <span>BUILD / VERIFIED</span></div></article><article class="security cyan"><div class="security-top">[ CYBERSECURITY SERVICES ] <b>02</b></div><div class="badge"><div class="seal">V</div><div><small>GUARANTEED SAFETY</small><strong>SECURITY INFRASTRUCTURE & PROTOCOL</strong></div></div><p>SECURED BY VALLÉE CYBER-DEFENCE</p><div class="statusline">PROTOCOL / ENFORCED <span>STATUS / SECURE</span></div></article></div><div class="footer-bottom"><span>© 2026 Wires & Stone. All Rights Reserved.</span><a href="https://www.instagram.com/wiresandstone" target="_blank" rel="noreferrer">@wiresandstone</a><a href="mailto:wiresandstone@gmail.com">wiresandstone@gmail.com</a></div></footer><button class="back" id="back">↑</button></div>`;

document.querySelector('#copy')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(email);const b=document.querySelector('#copy');b.innerHTML='COPIED — wiresandstone@gmail.com <b>✓</b>';setTimeout(()=>b.innerHTML='COPY EMAIL ADDRESS <b>▣</b>',2200)}catch{window.location.href='mailto:'+email}});
const back=document.querySelector('#back');window.addEventListener('scroll',()=>back.classList.toggle('show',scrollY>700));back.onclick=()=>scrollTo({top:0,behavior:'smooth'});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('on');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
